* Proposition de projet

Proposition de projet de développement dans le cadre du cours 420-G55.

La proposition doit être approuvée par l'enseignant. Par contre, les détails (sauf les membres de l'équipe) sont sujets à changement selon les circonstances au cours du développement avec l'accord de l'enseignant.

** Équipe

- Nom des coéquipiers (3 ou 4 personnes) :
  1 : Youssef Ayad
  2 : Taous Djellaoui
  3 : Kindy Ariste
  4 : Yudas Amer
  
- Horaire de rencontre hebdomadaire (1h) : Lundi de 11h à 12h ou mercredi de 12h à 13h

** Projet

- Thématique (quel est le domaine d'application de votre travail) : Application de vente de Vinyles
  
- Problème à résoudre (du point de vue de l'utilisateur, quel sera la plus-value de votre app) : Permettre aux utilisateurs de vendre ou d'acheter des vinyles 
  
- Analyse comparative (nommez au moins deux applications (Android ou non) déjà existantes qui font plus ou moins la même chose) : Amazon, rakuten, Kijiji

  
** Fonctionnalités minimales : Mettre en vente des vinyles, acheter des vinyles, rechercher des vinyles, contacter les vendeurs, noter les vendeurs.

*** Sauvegarde locale d'informations utilisateurs
Quelles données comptez-vous stoquer localement sur l'appareil? : préférence de langue, historique des recherches 

*** Échange de données avec un service extérieur
Quelles données comptez-vous échanger avec un service extérieur? : transactions, liste des acheteurs, vendeurs et vinyles. 


L'API existe-t-il déjà? : Non pas encore
Si oui, est-il accessible librement? gratuitement? devez-vous l'héberger vous-même? : Nous l'hebergons nous même
Si non, sera-t-il développé et par qui? ou simulé? : 
Si déjà connu, de quel type d'API s'agit-il?
  - REST

*** Interaction avec d'autres applications du système Android
Quelle(s) fonctionnalité(s] fer(a|ont) appel à une autre application du système? Envoie d'email pour contacter les vendeurs ou utiliser une application tiers pour ajouter des photos du produit.
(ex.: prise de photo/vidéo, envoie de courriel, ajout de rendez-vous au calendrier, etc.) : envoie de courriel, utiliser l'appareil photo


*** Licence choisie :
- ☐ Propriétaire
